#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user:
  type: rest
  resource: App\Controller\UserController
group:
  type: rest
  resource: App\Controller\GroupController